
reporter: "xcode"
line_length:
- 200
- 300
function_body_length:
- 80
file_length:
- 600
- 2000
cyclomatic_complexity:
- 20
type_body_length:
- 400
variable_name:
min_length:
- 1
max_length:
- 60
excluded:
- Pods
- ../FirebaseChatXTests
- ../FirebaseChatXUITests
disabled_rules:
- trailing_newline
- trailing_whitespace
- vertical_parameter_alignment
- function_parameter_count
- private_over_fileprivate
- line_length
